import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

import { ReactLenis } from "./utils/lenis";

import { ScrollProgress, Banner, Navbar, Footer } from "./components";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EV Charge Inc - Electric Vehicle Charging Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body className={`${manrope.variable} antialiased`}>
          <ScrollProgress />

          <Navbar />
          {children}
          <Footer />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
          <br />
        </body>
      </ReactLenis>
    </html>
  );
}
